# Default values for app-languages.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

appData:
  labelValue: "nginx-webapp"
  imageName: "whatthehackmsft/nginxserver"
  imageVersion: "latest"
  namespace: "whatthehack"

serviceDefinition:
  name: "webapp-loadbalancer"
  type: "LoadBalancer"
   
