apiVersion: apps/v1
kind: Deployment
metadata:
  name: langfacts
  namespace: whatthehack
  labels:
    k8s-app: langfacts
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: langfacts
  template:
    metadata:
      labels:
        k8s-app: langfacts
    spec:
      containers:
      - name: langfacts
        image: whatthehackmsft/langfacts:v1
        env:
          - name: HACK_YEAR
            value: "2018"
          - name: HACK_MONITORING_ENABLED
            value: "false"
          - name: HACK_SECURITY_ENABLED
            value: "false"
        ports:
        - containerPort: 80
          name: ui
          protocol: TCP