apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-webapp
  namespace: whatthehack
  labels:
    k8s-app: nginx-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: nginx-webapp
  template:
    metadata:
      labels:
        k8s-app: nginx-webapp
    spec:
      containers:
      - name: nginx-webapp
        image: whatthehackmsft/nginxserver:v1
        env:
          - name: HACK_YEAR
            value: "2018"
          - name: HACK_MONITORING_ENABLED
            value: "false"
          - name: HACK_SECURITY_ENABLED
            value: "false"
        ports:
        - containerPort: 80
          name: ui
          protocol: TCP