apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: azure-volume-file
  name: azure-volume-file
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: azure-volume-file
      name: azure-volume-file
    spec:
      containers:
      - name: busybox-writer
        image: busybox
        command:
        - sh
        - -c
        - "while true; do sleep 1; echo $(date +%Y-%m-%d:%H:%M:%S) - $(hostname) >> /azure-volume-file/index.html; done"
        volumeMounts:
        - mountPath: /azure-volume-file
          name: azure-volume-file
      - name: busybox-web
        image: busybox
        command:
        - sh
        - -c
        - "httpd -p 80 -f -v -h /azure-volume-file"
        volumeMounts:
        - mountPath: /azure-volume-file
          name: azure-volume-file
      volumes:
      - name: azure-volume-file
        persistentVolumeClaim:
          claimName: azure-file-pvc
