---

- name: Install unzip
  package:
    name: unzip
    state: present

- name: Check whether the installation media already exists and has been extracted
  stat: path={{ hana_software_loc }}
  register: extract_path_status

- name: transfer installation media to hanadbnodes
  copy:
    src: "{{ item }}"
    dest: "{{ azure_files_mount_path }}/DB/"
  with_fileglob:
    - "{{ azure_files_mount_path }}/DB/*.ZIP" 
  when: extract_path_status.stat.exists == false

- name: Identify media archive
  shell: "ls {{ azure_files_mount_path }}/DB|grep ZIP"
  register: bits_file

- name: Extract media archive
  unarchive: 
    src: "{{ azure_files_mount_path }}/DB/{{ bits_file.stdout }}"
    dest: "{{ azure_files_mount_path }}/DB"
    remote_src: yes
    creates: "{{ hana_software_loc }}"
