---

# Implement manual preparation steps for all OS
# The tasks' name follows:
#   - SAP Notes for RHEL OS recommendations

# RHEL-3.10 Disable Transparent Hugepages (THP)
# RHEL-3.12 Configure Processor C-States (not relevant for IBM Power LE (ppc64le))
# SAP Note 2205917 - SAP HANA DB Recommended OS settings for SLES 12 / SLES for SAP Applications 12
- name: Task Disable Transparent Hugepages & Configure Processor C-States 1
  command: "echo never > /sys/kernel/mm/transparent_hugepage/enabled"

- name: Task Disable Transparent Hugepages & Configure Processor C-States 2
  lineinfile: 
     dest: /etc/default/grub 
     regexp: "GRUB_CMDLINE_LINUX=" 
     line: "GRUB_CMDLINE_LINUX='crashkernel=auto  @ vconsole.keymap=us @kernel_arguments: transparent_hugepage=never intel_idle.max_cstate=1 processor.max_cstate=1'"

- name: Task Disable Transparent Hugepages & Configure Processor C-States 3
  command: grub2-mkconfig -o /boot/grub2/grub.cfg

# If current host is LargeInstance, creating swap will be skipped. 
- name: Prepare SWAP
  when: hana_database.size != "LargeInstance"
  block:
  
  - name: Configure SWAP space
    lineinfile:
      dest: /etc/waagent.conf
      regexp: "^{{ item.prop }}="
      line: "{{ item.prop }}={{ item.value }}"
    with_items:
      - { prop: "ResourceDisk.Format", value: "y" }
      - { prop: "ResourceDisk.EnableSwap", value: "y" }
      - { prop: "ResourceDisk.SwapSizeMB", value: "{{ (hdb_sizes[hana_database.size].compute.swap_size_gb) * 1024|int }}" }

  - name: Restart waagent
    service:
      name: waagent 
      state: restarted
