replicaCount: 1

# Change the application settings here
appConfig:
  databaseType: "oracle" # mysql or postgres
  dataSourceURL: "jdbc:oracle:thin:@//10.71.210.209:1521/xe" # your JDBC connection string goes here.
  dataSourceUser: "C##WTH" # your database username goes here
  dataSourcePassword: "OCPHack8" # your database password goes here
  webPort: 8083 # the port the app listens on
  webContext: "pizzeria" # the application context http://hostname:port/webContext

infrastructure:
  namespace: contosoapporacle
