---
- hosts: hdb0
  roles:
    - { role: imds-reg, scenario: "hana-singlenode", deploy_status: "started"}

- hosts: "hdb0"
  become: true
  roles:
    - disk-setup
    - hotfix
    - saphana-install
    - { role: xsa-install, when: install_xsa == true }
    - { role: cockpit-download, when: install_xsa == true and install_cockpit == true }

- hosts: "hdb0"
  become: true
  become_user: "{{ sap_sid|lower }}adm"
  roles:
    - { role: shine-install, when: install_xsa == true and install_shine == true }
    - { role: cockpit-install, when: install_xsa == true and install_cockpit == true }
    - { role: webide-install, when: install_xsa == true and install_webide == true }

- hosts: win_bastion
  connection: winrm
  vars:
    ansible_user: "{{ bastion_username_windows }}"
    ansible_password: "{{ pw_bastion_windows }}"
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore
  roles:
    - set-up-windows-bastion

- name: run playbook for linux bastion host
  vars:
    config_json_file: ../modules/single_node_hana/temp.json
  import_playbook: linux_bastion_host.yml

- hosts: hdb0
  roles:
    - { role: imds-reg, scenario: "hana-singlenode", deploy_status: "finished"}
