name: Spell Check

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
    branches: [FixSpellCheck]
    paths:
      - "**.md"

jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@2036da178f85576f1940fedb74bb93a36cd89ab7
        with:
          files: |
            **/*.md
      - uses: ./.github/actions/spell-check
        name: WTH Spell Check
        with:
          spell_check_yaml_path: .github/workflows/spell-check/spellcheck.yml
          markdown_base_path: .
          changed_files: ${{ steps.changed-files.outputs.all_changed_files }}
